In [4]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline 
from sklearn import preprocessing 


In [11]:
churn_df = pd.read_csv('ChurnData.csv')

In [12]:
df.head(25)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0     11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1     33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2     23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3     38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4      7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
5     68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0   
6     42.0  40.0      7.0    37.0  2.0     8.0    1.0       1.0       1.0   
7      9.0  21.0      1.0    17.0  2.0     2.0    0.0       0.0       0.0   
8     35.0  50.0     26.0   140.0  2.0    21.0    0.0       1.0       0.0   
9     49.0  51.0     27.0    63.0  4.0    19.0    0.0       1.0       0.0   
10    56.0  52.0     28.0    49.0  2.0    12.0    0.0       1.0       0.0   
11    47.0  40.0     16.0   127.0  4.0    12.0    1.0       1.0       0.0   
12    56.0  50.0      1.0    80.0  2.0    24.0    0.0       1.0       1.0   
13    69.0  51.0     11.0   438.0  4.0    23.0    1.0       1.0       0.0   
14    16.0  27.0      5.0    37.0  3.0     5.0    0.0       0.0       0.0   
15     4.0  35.0     16.0   161.0  5.0     6.0    1.0       0.0       1.0   
16    27.0  51.0      3.0    80.0  5.0    11.0    1.0       0.0       0.0   
17    52.0  61.0      3.0    53.0  5.0     1.0    1.0       1.0       1.0   
18    64.0  25.0      4.0    76.0  3.0     2.0    1.0       1.0       0.0   
19    12.0  24.0      2.0    19.0  1.0     0.0    0.0       1.0       0.0   
20    35.0  61.0     23.0    41.0  2.0    11.0    0.0       1.0       0.0   
21    13.0  54.0      2.0    31.0  4.0     2.0    0.0       0.0       0.0   
22    45.0  22.0      2.0    36.0  4.0     0.0    1.0       0.0       0.0   
23     3.0  37.0     13.0    24.0  1.0     3.0    0.0       0.0       0.0   
24    53.0  22.0      1.0    25.0  4.0     0.0    1.0       1.0       0.0   

    longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0      4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1      9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2      6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3      6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4      7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
5     20.70  ...    0.0       0.0       0.0     0.0    0.0    3.030    3.240   
6      8.25  ...    0.0       1.0       1.0     1.0    1.0    2.110    3.157   
7      2.90  ...    0.0       0.0       0.0     0.0    0.0    1.065    3.240   
8      6.50  ...    0.0       0.0       1.0     1.0    0.0    1.872    3.314   
9     12.85  ...    0.0       1.0       1.0     0.0    1.0    2.553    3.248   
10    24.75  ...    0.0       0.0       0.0     0.0    0.0    3.209    3.240   
11    19.70  ...    0.0       1.0       0.0     0.0    1.0    2.981    3.240   
12    28.80  ...    1.0       0.0       1.0     1.0    0.0    3.360    4.016   
13    29.00  ...    1.0       1.0       0.0     1.0    0.0    3.367    3.240   
14     6.00  ...    0.0       0.0       0.0     0.0    0.0    1.792    3.240   
15     3.40  ...    1.0       1.0       1.0     1.0    1.0    1.224    3.168   
16     7.10  ...    1.0       1.0       0.0     0.0    1.0    1.960    3.240   
17    12.25  ...    0.0       1.0       0.0     1.0    1.0    2.506    3.240   
18    24.05  ...    0.0       0.0       0.0     1.0    1.0    3.180    3.240   
19     4.00  ...    0.0       0.0       1.0     1.0    0.0    1.386    3.209   
20     9.60  ...    0.0       0.0       0.0     0.0    0.0    2.262    3.240   
21     5.85  ...    0.0       1.0       0.0     0.0    1.0    1.766    3.240   
22     9.95  ...    0.0       0.0       0.0     0.0    0.0    2.298    2.691   
23     2.00  ...    0.0       0.0       0.0     1.0    1.0    0.693    3.240   
2

In [13]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
churn_df['churn'] = churn_df['churn'].astype('int')

In [14]:
churn_df.head(10)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
5    68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0   
6    42.0  40.0      7.0    37.0  2.0     8.0    1.0       1.0       1.0   
7     9.0  21.0      1.0    17.0  2.0     2.0    0.0       0.0       0.0   
8    35.0  50.0     26.0   140.0  2.0    21.0    0.0       1.0       0.0   
9    49.0  51.0     27.0    63.0  4.0    19.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0  
5      0  
6      0  
7      0  
8      0  
9      0

In [19]:
churn_df.describe()


tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless       churn  
count  200.000000  200.000000  200.000000  200.000000  
mean     0.425000    0.705000    0.290000    0.290000  
std      0.495584    0.457187    0.454901    0.454901  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000  
50%      0.000000    1.000000    0.000000    0.000000  
75%      1.000000    1.000000    1.000000    1.000000  
max      1.000000    1.000000    1.000000    1.000000

In [22]:
churn_df.shape

(200, 10)

In [23]:
X = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']]) 
y = np.asarray(churn_df[['churn']])

In [25]:
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [28]:
X = preprocessing.StandardScaler().fit(X).transform(X) 

In [29]:
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [30]:
from sklearn.model_selection import train_test_split 

In [31]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape) 

Train set: (160, 7) (160, 1)
Test set: (40, 7) (40, 1)


In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix 

In [33]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train) 

C:\Users\21355\anaconda\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [34]:
LR

LogisticRegression(C=0.01, solver='liblinear')

In [35]:
yhat = LR.predict(X_test)
yhat 

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [36]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob 

array([[0.54132919, 0.45867081],
       [0.60593357, 0.39406643],
       [0.56277713, 0.43722287],
       [0.63432489, 0.36567511],
       [0.56431839, 0.43568161],
       [0.55386646, 0.44613354],
       [0.52237207, 0.47762793],
       [0.60514349, 0.39485651],
       [0.41069572, 0.58930428],
       [0.6333873 , 0.3666127 ],
       [0.58068791, 0.41931209],
       [0.62768628, 0.37231372],
       [0.47559883, 0.52440117],
       [0.4267593 , 0.5732407 ],
       [0.66172417, 0.33827583],
       [0.55092315, 0.44907685],
       [0.51749946, 0.48250054],
       [0.485743  , 0.514257  ],
       [0.49011451, 0.50988549],
       [0.52423349, 0.47576651],
       [0.61619519, 0.38380481],
       [0.52696302, 0.47303698],
       [0.63957168, 0.36042832],
       [0.52205164, 0.47794836],
       [0.50572852, 0.49427148],
       [0.70706202, 0.29293798],
       [0.55266286, 0.44733714],
       [0.52271594, 0.47728406],
       [0.51638863, 0.48361137],
       [0.71331391, 0.28668609],
       [0.

In [37]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat,pos_label=0) 

0.7058823529411765

In [38]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob) 

0.6017092478101185