In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split 
%matplotlib inline 

In [2]:
dataset = pd.read_csv('cell_samples.csv')

In [3]:
dataset.head(25)

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0   1000025      5         1          1        1            2       1   
1   1002945      5         4          4        5            7      10   
2   1015425      3         1          1        1            2       2   
3   1016277      6         8          8        1            3       4   
4   1017023      4         1          1        3            2       1   
5   1017122      8        10         10        8            7      10   
6   1018099      1         1          1        1            2      10   
7   1018561      2         1          2        1            2       1   
8   1033078      2         1          1        1            2       1   
9   1033078      4         2          1        1            2       1   
10  1035283      1         1          1        1            1       1   
11  1036172      2         1          1        1            2       1   
12  1041801      5         3          3        3            2       3   
13  1043999      1         1          1        1            2       3   
14  1044572      8         7          5       10            7       9   
15  1047630      7         4          6        4            6       1   
16  1048672      4         1          1        1            2       1   
17  1049815      4         1          1        1            2       1   
18  1050670     10         7          7        6            4      10   
19  1050718      6         1          1        1            2       1   
20  1054590      7         3          2       10            5      10   
21  1054593     10         5          5        3            6       7   
22  1056784      3         1          1        1            2       1   
23  1057013      8         4          5        1            2       ?   
24  1059552      1         1          1        1            2       1   

    BlandChrom  NormNucl  Mit  Class  
0            3         1    1      2  
1            3         2    1      2  
2            3         1    1      2  
3            3         7    1      2  
4            3         1    1      2  
5            9         7    1      4  
6            3         1    1      2  
7            3         1    1      2  
8            1         1    5      2  
9            2         1    1      2  
10           3         1    1      2  
11           2         1    1      2  
12           4         4    1      4  
13           3         1    1      2  
14           5         5    4      4  
15           4         3    1      4  
16           2         1    1      2  
17           3         1    1      2  
18           4         1    2      4  
19           3         1    1      2  
20           5         4    4      4  
21           7        10    1      4  
22           2         1    1      2  
23           7         3    1      4  
24           3         1    1      2

In [4]:
dataset.dtypes

ID              int64
Clump           int64
UnifSize        int64
UnifShape       int64
MargAdh         int64
SingEpiSize     int64
BareNuc        object
BlandChrom      int64
NormNucl        int64
Mit             int64
Class           int64
dtype: object

In [5]:
## transformation de barenuc to numiric 
dataset = dataset[pd.to_numeric(dataset['BareNuc'], errors='coerce').notnull()]
dataset['BareNuc'] = dataset['BareNuc'].astype('int')

In [6]:
dataset.dtypes

ID             int64
Clump          int64
UnifSize       int64
UnifShape      int64
MargAdh        int64
SingEpiSize    int64
BareNuc        int32
BlandChrom     int64
NormNucl       int64
Mit            int64
Class          int64
dtype: object

In [7]:
features_df =  dataset[['Clump' ,'UnifSize' ,'UnifShape','MargAdh','SingEpiSize','BareNuc','BlandChrom','NormNucl','Mit']]
X = np.asarray(features_df)

In [8]:
X[0:5]

array([[ 5,  1,  1,  1,  2,  1,  3,  1,  1],
       [ 5,  4,  4,  5,  7, 10,  3,  2,  1],
       [ 3,  1,  1,  1,  2,  2,  3,  1,  1],
       [ 6,  8,  8,  1,  3,  4,  3,  7,  1],
       [ 4,  1,  1,  3,  2,  1,  3,  1,  1]], dtype=int64)

In [9]:
y = np.asarray(dataset['Class'])

In [10]:
dataset['Class'] = dataset['Class'].astype('int')

In [11]:
y = np.asarray(dataset['Class'])

 

In [12]:
y[0 : 5]

array([2, 2, 2, 2, 2])

In [13]:
y[0 : 5]

array([2, 2, 2, 2, 2])

In [14]:
## spliting  the data 

In [15]:
X_train , X_test , y_train , y_test  = train_test_split( X, y , test_size = 0.2 , random_state = 4 )

In [16]:
print (' train shape :  '  , X_train.shape  , y_train.shape ) 
print (' test shape :  '  ,  X_test.shape , y_test.shape ) 


 train shape :   (546, 9) (546,)
 test shape :   (137, 9) (137,)


In [17]:
## modeling using the SVM 

In [18]:
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier  
from sklearn import tree

In [19]:
clf = svm.SVC(kernel ='rbf')
model =  DecisionTreeClassifier()

In [20]:
clf.fit(X_train , y_train )


SVC()

In [21]:
yhat = clf.predict(X_test)

In [22]:
yhat[0:10]

array([2, 4, 2, 4, 2, 2, 2, 2, 4, 2])

In [23]:
y_test[0:10]

array([2, 4, 2, 4, 2, 2, 2, 2, 4, 2])

In [24]:
## evalution

In [30]:
from sklearn.metrics import f1_score  
from sklearn.metrics import accuracy_score  

In [33]:

accuracy01 =  accuracy_score(y_test , yhat)

In [34]:
print ( ' accurracy is :  '  , accuracy01* 100 ) 


 accurracy is :   96.35036496350365


In [35]:
model = DecisionTreeClassifier(criterion = 'entropy' , max_depth = 4)

In [36]:
model.fit(X_train , y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [37]:
ypred = model.predict(X_test)

In [38]:
ypred[0:5]

array([2, 4, 2, 4, 2])

In [39]:
y_test[0:5]

array([2, 4, 2, 4, 2])

In [40]:
from sklearn import metrics 

In [41]:
accuracy =  metrics.accuracy_score(y_test , ypred)

In [42]:
accuracy * 100 

97.08029197080292